### PR TITLE
Rotate manipulators to ensure every fix is run at least once

### LINKED ISSUE #33: Runner accidentally skips manipulators when errors are repeated
There is a bug where the runner doesn't get to fix for all of the flags because it skips manipulators and prematurely exits the judgement loop because the same errors appear after one of the earlier manipulators isn't able to fix them. To fix this, we need to ensure that the runner is able to get through all of the manipulators at least once before exiting the judgement loop.

### PR DESCRIPTION
**Pull request by guor8lei**
Fixes #33. Two main fixes:

1. While fixing for noImplicitAny, I noticed that there was a bug in the judgement while loop in my `Runner` class. Namely, when one of the earlier manipulators in the list (say, `StrictNullChecksManipulator`) fixes for some errors but is not able to fix for all errors, those same errors appear in the next iteration of the judgement loop. Because we are checking between each iteration if the errors are the same, that means that the runner is prematurely exiting this loop before going through all the manipulators. The way I fixed this was to ensure that every manipulator was "checked/run" at least once, by rotating the list of manipulators. That way, once manipulator N implements its fixes, in the next iteration of the judgement loop, the runner first starts with checking manipulator N+1 and so on.

2. In addition, I noticed that in general, because `StrictNullChecksManipulator` is responsible for adding `null` and `undefined` types to variable and parameter declarations, it would be more helpful to first address `-strictNullChecks` before doing the type inference in `NoImplicitAnyManipulator`. As a a result, I reordered the manipulator list to reflect this. Doing this should not change the implementation result, rather just reducing the number of iterations of fixes that's required to achieve the same result.

### CODE REVIEW

File: src/runner.ts [hunk 1]
```diff
@@ -89,11 +89,16 @@ export class Runner {
...
-    let errorsExist;
+    let errorsExist: boolean;
+    let rotatedManipulators: Manipulator[];
 
     do {
       errorsExist = false;
+      rotatedManipulators = [...this.manipulators];
+
       for (const manipulator of this.manipulators) {
+        rotatedManipulators.push(rotatedManipulators.shift()!);
```
Comment (michaelyara) [inline src/runner.ts:100]: You may want to add a little comment here about what you are doing. I took me a while to figure out that you are just rotating elements in the array FIFO. The line looks odd at first. I fact you may want to comment on the core issue you are solving.

Comment (guor8lei) [reply src/runner.ts:103]: That's a good point, I've gone ahead and added more comments making it clearer how the Runner is working!
